# Python_Testcases
# How to run project for Positive_unittest:

python Positive_unittest.py                                                                                           
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK

# How to run project for Negative_unittest:

python Negative_unittest.py
F
======================================================================
FAIL: test_negative (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python_testcases\Negative_unittest.py", line 12, in test_negative
    self.assertEqual(a,b,message)
AssertionError: 'Jignesh' != 'nidhi'
- Jignesh
+ nidhi
 : These values are  not equal

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
![image](https://user-images.githubusercontent.com/102863684/191179806-cd3904ed-db1e-4b49-a71b-76348e1f4dad.png)
